[project]
name = telegram_compare_cjmp
description = A new keels project.
type = app
organization = com.example

# You can add other keels logic-module or module project as dependencies.
# [dependencies]
# packageName = /path/to/logic-module
# moduleName = /path/to/module
